### ISSUE TITLE
docs on parameter choice

### ISSUE THREAD

**Issue by brentp** [ekzhu/lsh#2]
thanks for implementing this!

I am interested in using the LSH-Forest after reading the Bawa et al paper. The docs for the constructor look like:
```
l is the number of hash tables to use, m is the number of hash values to concatenate to form the key to the hash tables, w is the slot size for the family of LSH functions.
```

+ The paper says to just set `l` large enough, e.g. 10.
+ I think the `m` in the function sig is `k` from the paper or, specifically km (the maximum label length == maximum number of hashes. correct?
+ I see that `w` [is used to scale the hash-value](https://github.com/ekzhu/lsh/blob/master/lsh.go#L66). How does one choose this value? Is this what the Bawa paper defines as `cl` the number of colliding points that are then filtered to the closest k-nearest?

thanks,
-Brent

**Comment by ekzhu** [comment]
Yes. The definition of `l` and `m` are correct.

Setting `w` is tricky. Essentially it is used to set how likely hash values should collide when they are similar. Imaging the hash values being scattered over a 1-D line (which is a gaussian random vector), the `w` is used to "segment" that line into sections of length `w`. So hash values fall into the same section are declared as equal.

So, you can set some large enough value of `w` so that the forest index returns something. Setting the parameter optimally requires adapting it to the data distribution. See the multiprobe LSH paper.
